# Generated by Django 3.2.23 on 2024-01-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='table',
            field=models.TextField(choices=[('1', 'Bigger table by window'), ('2', 'Smaller table by window'), ('3', 'Big table in isle')], max_length=255),
        ),
    ]
