# Generated by Django 3.2.23 on 2024-01-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_reservation_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='table',
            field=models.TextField(choices=[('1', 'Bigger table by window'), ('2', 'Smaller table by window'), ('3', 'Big table in isle'), ('4', 'small table in isle')], max_length=255),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TextField(choices=[('3-5', '3pm-5pm'), ('5-7', '5pm-7pm'), ('7-9', '7pm-9pm')], max_length=255),
        ),
    ]
